name: Create Sentry Release
description: 'Automatically create a Sentry release in a workflow'

inputs:
  project:
    description: 'Project name in organization'
    required: true
  auth-token:
    description: 'Auth token'
    required: true
  org:
    description: 'Org name in organization'
    required: true
  env:
    description: 'Environment: stage or prod'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Get current time (Kyiv)
      id: current-time
      shell: bash
      run: echo "current-time=$(TZ='Europe/Kyiv' date '+%H:%M %d.%m.%y')" >> $GITHUB_ENV

    - name: Create Sentry release
      uses: getsentry/action-release@v1.7.0
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.auth-token }}
        SENTRY_ORG: ${{ inputs.org }}
        SENTRY_PROJECT: ${{ inputs.project }}
      with:
        environment: ${{ inputs.env }}
        version: ${{ env.current-time }}
        started_at: ${{ steps.current_time.outputs.unix_timestamp }}
