name: "Invalidate CloudFront"
description: "Invalidate one or multiple CloudFront distributions with retries"

inputs:
  distribution:
    description: "CloudFront Distribution ID or multiple IDs separated by comma/space/newline"
    required: true
  retrying:
    description: "Retry count per distribution"
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI v2
      shell: bash
      run: |
        echo "Installing AWS CLI v2..."
        sudo rm -rf /usr/local/aws-cli /usr/local/bin/aws || true
        curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Invalidate CloudFront Distributions
      shell: bash
      run: |
        distributions=$(echo "${{ inputs.distribution }}" | tr ',\n' ' ' | tr -s ' ')
        echo "Distributions to invalidate (in parallel):"
        echo "$distributions"

        failed=()

        invalidate_distribution() {
          local dist_id=$1
          echo "Starting invalidation for $dist_id"
          for i in $(seq 1 ${{ inputs.retrying }}); do
            echo "Attempt #$i for $dist_id"
            if aws cloudfront create-invalidation \
              --distribution-id "$dist_id" \
              --paths "/*" \
              --caller-reference "$(date +%s)-$dist_id-$i"; then
              echo "Invalidation succeeded for $dist_id"
              return 0
            else
              echo "Failed attempt #$i for $dist_id, retrying in $((i * 10)) seconds..."
              sleep $((i * 10))
            fi
          done
          echo "All attempts failed for $dist_id"
          failed+=("$dist_id")
          return 1
        }

        export -f invalidate_distribution
        export failed

        for dist_id in $distributions; do
          invalidate_distribution "$dist_id" &
        done

        wait

        if [ "${#failed[@]}" -gt 0 ]; then
          echo "Some invalidations failed:"
          printf ' - %s\n' "${failed[@]}"
          exit 1
        fi

        echo "All invalidations completed successfully!"
