name: "Invalidate CloudFront"
description: "Invalidate one or multiple CloudFront distributions in parallel with retries"

inputs:
  distribution:
    description: "One or multiple CloudFront Distribution IDs (comma, space, or newline separated)"
    required: true
  retrying:
    description: "Retry count per distribution"
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI v2
      shell: bash
      run: |
        echo "Installing AWS CLI v2..."
        sudo rm -rf /usr/local/aws-cli /usr/local/bin/aws /usr/bin/aws || true
        curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        /usr/local/bin/aws --version

    - name: Invalidate CloudFront Distributions (parallel)
      shell: bash
      run: |
        set -e
        export PATH="/usr/local/bin:$PATH"

        distributions=$(echo "${{ inputs.distribution }}" | tr ',\n' ' ' | tr -s ' ')
        echo "📦 Distributions to invalidate (in parallel):"
        echo "$distributions"

        mkdir -p /tmp/cf_invalidation
        rm -f /tmp/cf_invalidation/*

        invalidate_distribution() {
          local dist_id=$1
          echo "🚀 Starting invalidation for $dist_id"
          for i in $(seq 1 ${{ inputs.retrying }}); do
            echo "Attempt #$i for $dist_id"
            if /usr/local/bin/aws cloudfront create-invalidation \
              --distribution-id "$dist_id" \
              --paths "/*" \
              --caller-reference "$(date +%s)-$dist_id-$i" >/dev/null 2>&1; then
              echo "Invalidation succeeded for $dist_id"
              echo "success" > "/tmp/cf_invalidation/$dist_id"
              return 0
            else
              echo "Failed attempt #$i for $dist_id, retrying in $((i * 10)) seconds..."
              sleep $((i * 10))
            fi
          done
          echo "All attempts failed for $dist_id"
          echo "failed" > "/tmp/cf_invalidation/$dist_id"
          return 1
        }

        export -f invalidate_distribution

        for dist_id in $distributions; do
          bash -c "invalidate_distribution $dist_id" &
        done

        wait

        echo "Checking results..."
        if grep -q "failed" /tmp/cf_invalidation/* 2>/dev/null; then
          echo "Some invalidations failed:"
          grep -l "failed" /tmp/cf_invalidation/* | sed 's|.*/||'
          exit 1
        fi

        echo "All invalidations completed successfully!"