name: "Create PR master to stage"
description: "Create after release PR master to stage"

inputs:
  gh-token:
    description: "Authorization Bearer GH Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create PR
      shell: bash
      run: |
        curl --location --request POST 'https://api.github.com/repos/${{ github.repository }}/pulls' \
        --header 'Authorization: Bearer ${{ inputs.gh-token }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "head": "master",
          "base": "stage",
          "title": "master -> stage ${{ steps.date.outputs.date }}:",
          "body": "Marge master into stage after deploy"
        }'
